---
- hosts: localhost
  connection: local
  vars_files:
  - group_vars/all.yml
  roles:
  - homebrew-packages
  - suzuki-shunsuke.go-module
  - suzuki-shunsuke.ghq-module
  - go-packages
  - role: suzuki-shunsuke.vim-conf
    remote_repository_path: suzuki-shunsuke/vim.conf
  - role: suzuki-shunsuke.zsh-conf
    remote_repository_path: suzuki-shunsuke/zsh.conf
  - role: suzuki-shunsuke.zplug
  - role: suzuki-shunsuke.tmux-conf
    remote_repository_path: suzuki-shunsuke/tmux.conf
  - role: suzuki-shunsuke.gitconfig
    remote_repository_path: suzuki-shunsuke/git.conf
  - suzuki-shunsuke.gvm
  # - suzuki-shunsuke.gvm-dep-mac
  - suzuki-shunsuke.nodebrew
  - suzuki-shunsuke.neobundle-vim
  - suzuki-shunsuke.tmux-tpm
  - suzuki-shunsuke.docker-compose
  # - suzuki-shunsuke.pyenv-install-dep-mac
  - suzuki-shunsuke.pyenv
  # - suzuki-shunsuke.rbenv-install-dep-mac
  - suzuki-shunsuke.rbenv
  # - role: suzuki-shunsuke.colorrc
  #   remote_repository_path: suzuki-shunsuke/colorrc.conf
  # - suzuki-shunsuke.lang-ja-mac
  - zsh
  - suzuki-shunsuke.fzf
