---
- hosts: localhost
  vars_files:
  - group_vars/all.yml
  roles:
  - homebrew-packages
  - suzuki-shunsuke.go-module
  - suzuki-shunsuke.ghq-module
  - go-packages
  #   - role: suzuki-shunsuke.vim-conf
  #     remote_repository_path: suzuki-shunsuke/vim.conf
  - role: suzuki-shunsuke.neovim-mac
  - role: suzuki-shunsuke.neovim-conf
    neovim_conf_repo: suzuki-shunsuke/neovim.conf
    neovim_conf_undodir: "{{ansible_env.HOME}}/.local/share/nvim/undo"
  - role: suzuki-shunsuke.zsh-conf
    remote_repository_path: suzuki-shunsuke/zsh.conf
  - role: suzuki-shunsuke.zplug
  - role: suzuki-shunsuke.tmux-conf
    remote_repository_path: suzuki-shunsuke/tmux.conf
  - role: suzuki-shunsuke.gitconfig
    remote_repository_path: suzuki-shunsuke/git.conf
  - suzuki-shunsuke.gvm
  - suzuki-shunsuke.nodebrew
  # - suzuki-shunsuke.neobundle-vim
  - suzuki-shunsuke.tmux-tpm
  # - suzuki-shunsuke.docker-compose
  - role: suzuki-shunsuke.pyenv
    pyenv_is_dependencies_installed: yes
  - role: suzuki-shunsuke.rbenv
    rbenv_is_dependencies_installed: yes
  # - role: suzuki-shunsuke.colorrc
  #   remote_repository_path: suzuki-shunsuke/colorrc.conf
  # - suzuki-shunsuke.lang-ja-mac
  - zsh
  - suzuki-shunsuke.fzf
